import './globals.css'
import type { Metadata } from 'next'

import 'react-toastify/dist/ReactToastify.min.css';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'My-Auth-App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ToastContainer position="top-center"/>
        {children}
      </body>
    </html>
  )
}
